### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by sebastiaanluca** [vinkla/alfred-kaomoji#1]
Just upgraded to v1, but https://customer.getdango.com/dango/api/query/kaomoji seems to be down? Root domain doesn't work either.

**Comment by vinkla** [comment]
Oh no, I’ll check this tomorrow.

**Comment by vinkla** [comment]
It seems their are responding a 500 internal server error. I'll contact them.

**Comment by vinkla** [comment]
It seems to work again ¯⁠\_(ツ)_/⁠¯ Thanks for sharing it on Twitter (ﾉ⁠´ヮ⁠´)ﾉ*:･ﾟ⁠✧

**Comment by sebastiaanluca** [comment]
Still down here. Well, not down, but just an internal server error on their side.

Now I can't use kaomojis and have to use these awful emojis! 😩😛

**Comment by vinkla** [comment]
That is strange, it works fine for me. Maybe your requests are cached?

**Comment by sebastiaanluca** [comment]
Tried a few proxies and it seems to me their API is broken. Oh well!

**Comment by vinkla** [comment]
Too bad. I've emailed them. Lets see how it goes.
