### ISSUE TITLE
upgrade alfly for alfred 4

### ISSUE THREAD

**Issue by A1c0** [vinkla/alfred-kaomoji#8]
Can you please update alfly to be able to use this workflow on alfred 4 ?

**Comment by A1c0** [comment]
Sorry you use the last version, but can you publish this version ?

**Comment by vinkla** [comment]
Already released.

https://github.com/vinkla/alfred-kaomoji/compare/1.3.0...1.3.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
